---

- name: haproxy
  package:
    name: haproxy
    state: present

- name: haproxy.cfg
  copy:
    src: "{{ playbook_dir }}/files/{{ cfg }}"
    dest: /etc/haproxy/haproxy.cfg
    backup: yes
  notify: reload haproxy
  when: cfg is defined

# in a heartbeat cluster
# heartbeat is starting
# the service
#
- name: start haproxy
  service:
    name: "{{ haproxy_service }}"
    state: started
  when: haproxy_start_service

- name: check for pidfile
  stat:
    path: /var/run/haproxy.pid
  register: haproxy_pidfile

