---

- name: haproxy
  package:
    name: haproxy
    state: present

- name: haproxy.cfg
  template:
    src: "{{ playbook_dir }}/templates/{{ cfg }}"
    dest: /etc/haproxy/haproxy.cfg
    backup: yes
    validate: haproxy -c -f %s
  notify: reload haproxy
  when: cfg is defined

- debug: var=haproxy
  tags:
    - debug

# in a heartbeat cluster
# heartbeat is starting
# the service
#
- name: start haproxy
  service:
    name: "{{ haproxy_service }}"
    state: started
  when: haproxy.service.managed
