---

- name: haproxy
  package:
    name: haproxy
    state: present

- name: haproxy.cfg
  copy:
    src: "{{ playbook_dir }}/files/{{ cfg }}"
    dest: /etc/haproxy/haproxy.cfg
    backup: yes
    validate: haproxy -c -f %s
  notify: reload haproxy
  when: cfg is defined

# in a heartbeat cluster
# heartbeat is starting
# the service
#
- name: start haproxy
  service:
    name: "{{ haproxy_service }}"
    state: started
  when: haproxy_start_service

# ansible bug #350
# reload always starts service
# https://github.com/ansible/ansible-modules-core/issues/350
#
# gather info about the pid file
# and use it in reload handler
#
- name: check for pidfile
  stat:
    path: /var/run/haproxy.pid
  register: haproxy_pidfile
