---

- name: haproxy is installed
  package:
    name: haproxy
    state: present

- name: haproxy.cfg does exist
  when: not haproxy.external_config_file
  template:
    src: haproxy.conf.j2
    dest: /etc/haproxy/haproxy.cfg
    backup: yes
    validate: haproxy -c -f %s
  notify: reload haproxy

- name: haproxy.cfg does exist (externally provided)
  when: haproxy.external_config_file
  template:
    src: "{{ playbook_dir }}/{{ haproxy.external_config_file }}"
    dest: /etc/haproxy/haproxy.cfg
    backup: yes
    validate: haproxy -c -f %s
  notify: reload haproxy

- debug: var=haproxy
  tags:
    - never
    - debug

# in a heartbeat cluster
# heartbeat is starting
# the service
#
- name: start haproxy
  service:
    name: "{{ haproxy_service }}"
    state: started
  when: haproxy.service.managed
