#! set ft=yaml ts=2:
---

- name: log directory for haproxy does exist
  file:
    path: "{{ haproxy.logdir }}"
    state: directory

- name: rsyslog is configured for haproxy
  template:
    src: haproxy.conf.j2
    dest: /etc/rsyslog.d/haproxy.conf
  notify: reload rsyslog
