---

# ansible bug #350
# reload always starts service
# https://github.com/ansible/ansible-modules-core/issues/350
#
# this is suboptimal with heartbeat where haproxy is
# running only on _one_ system
#
# therefore a check for the haproxy pid file
#

- name: check for pidfile
  when: not haproxy.service.managed
  stat:
    path: /var/run/haproxy.pid
  register: haproxy_pidfile
  listen: reload haproxy

- name: reload haproxy
  service:
    name: haproxy
    state: reloaded
  when: haproxy.service.managed or haproxy_pidfile.stat.exists
